version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run:
          name: Update NPM
          command: sudo npm install -g npm@latest
      - run:
          name: Install Dependencies
          command: |
            sudo npm install -g grunt-cli codecov
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM packages
          command: npm ci
      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: grunt ci
      - run:
          name: Push Coverage
          command: codecov

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
